### ISSUE TITLE
Build fail in ree 1.8.7

### ISSUE THREAD

**Issue by miaout17** [wmorgan/leveldb-ruby#5]
It fails to build in ree 1.8.7-2011.01, but success in RMI 1.8.7 & 1.9.2

Error messages:

https://gist.github.com/344a509bddebfda56ea7

**Comment by wmorgan** [comment]
I can successfully build it with ree 1.8.7-2011.03. Are you able to build other gems with C components? Can you successfully e.g. `gem install whistlepig`?

**Comment by wmorgan** [comment]
Please reopen if this is still an issue for you.

**Comment by wmorgan** [comment]
I was finally able to reproduce this. This should be fixed in 0.9. Thanks for the bug report!
