### ISSUE TITLE
Crash when storing large object

### ISSUE THREAD

**Issue by ramayer** [wmorgan/leveldb-ruby#7]
``` ruby
 require 'leveldb'
db = LevelDB::DB.new "/tmp/asdf"
db.put "it really", "works" * 1000
```

gives me

<pre>
 [BUG] Segmentation fault
ruby 1.9.2p180 (2011-02-18 revision 30909) [i686-linux]

-- control frame ----------
c:0025 p:---- s:0093 b:0093 l:000092 d:000092 CFUNC  :make
c:0024 p:0017 s:0087 b:0087 l:000086 d:000086 METHOD /home/ron/.rvm/gems/ruby-1.9.2-p180/gems/leveldb-ruby-0.7/lib/leveldb.rb:11
c:0023 p:0019 s:0083 b:0083 l:000dd4 d:000098 EVAL   (irb):2
c:0022 p:---- s:0080 b:0080 l:000079 d:000079 FINISH
c:0021 p:---- s:0078 b:0078 l:000077 d:000077 CFUNC  :eval
c:0020 p:0028 s:0071 b:0071 l:000070 d:000070 METHOD /home/ron/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/irb/workspace.rb:80
c:0019 p:0033 s:0064 b:0063 l:000062 d:000062 METHOD /home/ron/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/irb/context.rb:254
c:0018 p:0031 s:0058 b:0058 l:00083c d:000057 BLOCK  /home/ron/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/irb.rb:159
c:0017 p:0042 s:0050 b:0050 l:000049 d:000049 METHOD /home/ron/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/irb.rb:273
c:0016 p:0011 s:0045 b:0045 l:00083c d:000044 BLOCK  /home/ron/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/irb.rb:156
c:0015 p:0144 s:0041 b:0041 l:000024 d:000040 BLOCK  /home/ron/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/irb/ruby-lex.rb:243
c:0014 p:---- s:0038 b:0038 l:000037 d:000037 FINISH
c:0013 p:---- s:0036 b:0036 l:000035 d:000035 CFUNC  :loop
c:0012 p:0009 s:0033 b:0033 l:000024 d:000032 BLOCK  /home/ron/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/irb/ruby-lex.rb:229
c:0011 p:---- s:0031 b:0031 l:000030 d:000030 FINISH
c:0010 p:---- s:0029 b:0029 l:000028 d:000028 CFUNC  :catch
c:0009 p:0023 s:0025 b:0025 l:000024 d:000024 METHOD /home/ron/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/irb/ruby-lex.rb:228
c:0008 p:0046 s:0022 b:0022 l:00083c d:00083c METHOD /home/ron/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/irb.rb:155
c:0007 p:0011 s:0019 b:0019 l:000584 d:000018 BLOCK  /home/ron/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/irb.rb:70
c:0006 p:---- s:0017 b:0017 l:000016 d:000016 FINISH
c:0005 p:---- s:0015 b:0015 l:000014 d:000014 CFUNC  :catch
c:0004 p:0183 s:0011 b:0011 l:000584 d:000584 METHOD /home/ron/.rvm/rubies/ruby-1.9.2-p180/lib/ruby/1.9.1/irb.rb:69
c:0003 p:0142 s:0006 b:0006 l:0008e4 d:001fc4 EVAL   /home/ron/.rvm/rubies/ruby-1.9.2-p180/bin/irb:16
c:0002 p:---- s:0004 b:0004 l:000003 d:000003 FINISH
c:0001 p:0000 s:0002 b:0002 l:0008e4 d:0008e4 TOP   
---------------------------
...
-- C level backtrace information -------------------------------------------
/home/ron/.rvm/rubies/ruby-1.9.2-p180/lib/libruby.so.1.9(rb_vm_bugreport+0x72) [0xaf97b2]
/home/ron/.rvm/rubies/ruby-1.9.2-p180/lib/libruby.so.1.9 [0x9d71f7]
/home/ron/.rvm/rubies/ruby-1.9.2-p180/lib/libruby.so.1.9(rb_bug+0x3a) [0x9d72ea]
/home/ron/.rvm/rubies/ruby-1.9.2-p180/lib/libruby.so.1.9 [0xa86e54]
[0x68b410]
/home/ron/.rvm/gems/ruby-1.9.2-p180/gems/leveldb-ruby-0.7/lib/leveldb/leveldb.so(_ZN7leveldb8SkipListIPKcNS_8MemTable13KeyComparatorEE6InsertERKS2_+0x38) [0x40bfc8]
/home/ron/.rvm/gems/ruby-1.9.2-p180/gems/leveldb-ruby-0.7/lib/leveldb/leveldb.so(_ZN7leveldb8MemTable3AddEyNS_9ValueTypeERKNS_5SliceES4_+0x136) [0x40b876]
/home/ron/.rvm/gems/ruby-1.9.2-p180/gems/leveldb-ruby-0.7/lib/leveldb/leveldb.so [0x4153d9]
/home/ron/.rvm/gems/ruby-1.9.2-p180/gems/leveldb-ruby-0.7/lib/leveldb/leveldb.so(_ZNK7leveldb10WriteBatch7IterateEPNS0_7HandlerE+0x200) [0x415760]
/home/ron/.rvm/gems/ruby-1.9.2-p180/gems/leveldb-ruby-0.7/lib/leveldb/leveldb.so(_ZN7leveldb18WriteBatchInternal10InsertIntoEPKNS_10WriteBatchEPNS_8MemTableE+0x53) [0x415933]
/home/ron/.rvm/gems/ruby-1.9.2-p180/gems/leveldb-ruby-0.7/lib/leveldb/leveldb.so(_ZN7leveldb6DBImpl14RecoverLogFileEyPNS_11VersionEditEPy+0x420) [0x4028d0]
/home/ron/.rvm/gems/ruby-1.9.2-p180/gems/leveldb-ruby-0.7/lib/leveldb/leveldb.so(_ZN7leveldb6DBImpl7RecoverEPNS_11VersionEditE+0x28e) [0x4065ae]
/home/ron/.rvm/gems/ruby-1.9.2-p180/gems/leveldb-ruby-0.7/lib/leveldb/leveldb.so(_ZN7leveldb2DB4OpenERKNS_7OptionsERKSsPPS0_+0xdf) [0x4067cf]
/home/ron/.rvm/gems/ruby-1.9.2-p180/gems/leveldb-ruby-0.7/lib/leveldb/leveldb.so [0x3fdc05]
/home/ron/.rvm/rubies/ruby-1.9.2-p180/lib/libruby.so.1.9 [0xae3909]
/home/ron/.rvm/rubies/ruby-1.9.2-p180/lib/libruby.so.1.9 [0xaf47ee]
/home/ron/.rvm/rubies/ruby-1.9.2-p180/lib/libruby.so.1.9 [0xae93df]
/home/ron/.rvm/rubies/ruby-1.9.2-p180/lib/libruby.so.1.9 [0xaee94a]
/home/ron/.rvm/rubies/ruby-1.9.2-p180/lib/libruby.so.1.9 [0xaef2bd]
/home/ron/.rvm/rubies/ruby-1.9.2-p180/lib/libruby.so.1.9(rb_f_eval+0xdc) [0xaef8ec]
/home/ron/.rvm/rubies/ruby-1.9.2-p180/lib/libruby.so.1.9 [0xae3958]
/home/ron/.rvm/rubies/ruby-1.9.2-p180/lib/libruby.so.1.9 [0xaf47ee]
/home/ron/.rvm/rubies/ruby-1.9.2-p180/lib/libruby.so.1.9 [0xae93df]
/home/ron/.rvm/rubies/ruby-1.9.2-p180/lib/libruby.so.1.9 [0xaee94a]
/home/ron/.rvm/rubies/ruby-1.9.2-p180/lib/libruby.so.1.9 [0xaf1937]
/home/ron/.rvm/rubies/ruby-1.9.2-p180/lib/libruby.so.1.9(rb_rescue2+0x169) [0x9d9989]
...

</pre>

**Comment by wmorgan** [comment]
I can't reproduce this, using ruby-1.9.2-p180. What is your system architecture and OS? What size values can you store? Is /tmp/ full, or anything weird like that?

**Comment by wmorgan** [comment]
Please reopen if this is reproducible.
